// export const produtos = [
//   {
//     id: 1,
//     image: './imgs/produtos/corel.png',
//     name: 'Arte CorelDraw',
//     title: 'a partir de',
//     price: '5.00',
//     category: "arte",
//   },
//   {
//     id: 2,
//     image: './imgs/produtos/01.caneca.png',
//     name: 'Caneca de Porcelana',
//     title: 'Arte a sua escolha',
//     price: '35.00',
//     category: "caneca",
//   },
//   {
//     id: 3,
//     image: './imgs/produtos/cafe.jpg',
//     name: 'Caneca de Porcelana',
//     title: 'Flork Café',
//     price: '35.00',
//     category: "caneca",
//   },
//   {
//     id: 4,
//     image: './imgs/produtos/caneca-jateada.jpg',
//     name: 'Caneca Jateada 500ml',
//     title: 'Paizão Nº1',
//     price: '50.00',
//     category: "caneca",
//   },
//   {
//     id: 5,
//     image: './imgs/produtos/flork.webp',
//     name: 'Almofada',
//     title: 'Flork Grávida',
//     price: '45.00',
//     category: "almofada",
//   },
//   {
//     id: 6,
//     image: './imgs/produtos/azulejo.jpg',
//     name: 'Azulejo',
//     title: 'Frase motivacional',
//     price: '40.00',
//     category: "azulejo",
//   },
//   {
//     id: 7,
//     image: './imgs/produtos/longdrink.png',
//     name: 'Copos Long Drink',
//     title: 'a partir de ',
//     price: '4.00',
//     category: "copo",
//   },
// ];
